name: Bump version

on:
  push:
    branches:
      - master

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/release-with-changelog@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-template: '- {date} {title} ← {hash}'
          template: |
              ### Changelog

              {commits}

              Compare: {range}

              ❤
